// Code generated by hertz generator.

package main

import (
	handler "affine-worker-go/biz/handler"
	"affine-worker-go/biz/handler/imageproxy"
	"affine-worker-go/biz/handler/linkpreview"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.Any("/image-proxy", imageproxy.ImageProxy)
	r.Any("/link-preview", linkpreview.LinkPreview)
	// your code ...
}
